name: Update data.txt every 5 minutes

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Se ejecuta cada 5 minutos

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Si tienes otros paquetes que instalar, agrégalos aquí

    - name: Run update_data.py script
      run: python app.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.csv
        git commit -m "Update data.txt with random values" || echo "No changes to commit"
        git push
