name: Update data_bumeran dayly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'  # Se ejecuta cada día a las 11pm

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Si tienes otros paquetes que instalar, agrégalos aquí

    - name: Download es_core_news_sm model for spaCy
      run: |
        python -m spacy download es_core_news_sm

    - name: Run update_data.py script
      env:
        SCRAPEOP_KEY: ${{ secrets.SCRAPEOP_KEY }}
      run: python app.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.csv
        git add bumeran_data_pure.csv
        git add data_bumeran.csv
        git add log.txt
        git commit -m "Update data.txt with random values" || echo "No changes to commit"
        git push
